### ISSUE TITLE
Add musicbrainz and userscripts topics to you repo

### ISSUE THREAD

**Issue by jesus2099** [y-young/userscripts#2]
Hi @y-young,
You could add **both [musicbrainz](https://github.com/topics/musicbrainz) and [userscripts](https://github.com/topics/userscripts) _topics_** to your GitHub repository so that we could find it more easily.
Click the **About** section's gear icon (⚙️) at the top right to add them.

This way we can find it along with others  in the MusicBrainz userscripts repository list: https://github.com/search?q=topic%3Amusicbrainz+topic%3Auserscripts

---

You already have userscripts topic set, there. 😉 👍 yeah

**Comment by y-young** [comment]
Done.✔
