### ISSUE TITLE
Adding support for separation using special characters

### ISSUE THREAD

**Issue by Roshri** [y-young/userscripts#6]
Hi! I really love your script as it really speeds up my proccess of importing releases to MB
I was wondering if some special characters could be added, or where should I modify the script myself.

I was reading through it and I understand the following characters are supported but I couldn't make it work `，、`  when I add some artists separated with these, the "Parse Artist Credits" does not separate them. If it's possible to fix this, I'd like to also add support for the `・` character since I'm finding it a lot on some releases

Once again, thank you for this cool script

**Comment by y-young** [comment]
> I was reading through it and I understand the following characters are supported but I couldn't make it work `，、` when I add some artists separated with these, the "Parse Artist Credits" does not separate them. 

They'll work if preceded by a ')', like `(CV.ABC)、`, but it seems I forgot they could be used independently, will fix it later.

> If it's possible to fix this, I'd like to also add support for the `・` character since I'm finding it a lot on some releases

Sure, simply change `JOIN_PHRASE_PATTERN` to `\s*(?:\(CV[\.:： ]?|\)[,，、]?|\s(?:featuring|feat|ft|vs)[\.\s]|,|、|，|&|・)\s*` (this also fixes the first one). It'd be better if you can provide some examples how it's used. 

Please tell me if it's working correctly after you tried it.

**Comment by Roshri** [comment]
Yup, that was the very same release I added today and sparked this issue!

Just gave it a try and it seems to work flawlessly now!

![image](https://user-images.githubusercontent.com/29184137/168407898-3962c257-f8e2-4b9b-a14c-2eba13fc0762.png)

**Comment by y-young** [comment]
I didn't know '・' is used with 'CV', I'm trying to figure out how to make it work.

**Comment by y-young** [comment]
I think I've figured it out, try `\s*(?:\(CV[\.:： ]?|\)\s*[,，、・]?|\s(?:featuring|feat|ft|vs)[\.\s]|,|，|、|&|・)\s*`.

**Comment by Roshri** [comment]
Adding a dummy release with a similar format and it looks like this when trying it out now

![image](https://user-images.githubusercontent.com/29184137/168408536-93f17062-83a8-40df-b27c-242c3f3c3636.png)

I think it works as intended now! Thanks!
